### ISSUE TITLE
query() and requery() performance on large bundles is impossible

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#100]
A query() call with dominance relation ('^')  or a requery_hier() call on a emuDB with exceptional large numbers of segments within a bundle can be impossible slow.
(A simple query() call without dominance relation has a normal processing time.)
For example a requery_hier() on the Rhapsodie corpus from the phonetic level to the word level based on a emuRsegs list with 1200 elements took more than 8h and then the R process terminated without a result.
The Rhapsodie corpus has very few bundles (52) but some of them have more than 500 segments!
(The Rhapsodie emuDB is on IPS servers in /vdata/BAS/Rhapsodie/emuR/Rhapsodie/)

**Comment by raphywink** [comment]
Fixed this a while ago (was due to a bad index on one of our SQL tables that was slowing down searching within bundles). This query on `/vdata/BAS/Rhapsodie/emuR/Rhapsodie/`:

```r
> system.time(query(rhap, "[SAP = n ^ ORT =~.*]"))
       User      System verstrichen
     24.732       0.894      28.284
````

terminates in 28 secs on my Laptop which isn't too bad.
