### ISSUE TITLE
Unique constraint for bundle item IDs

### ISSUE THREAD

**Issue by klausj** [IPS-LMU/emuR#106]
To avoid duplicate item IDs in bundles add UNIQUE constraint on item table over columns session,bundle and itemID.

**Comment by raphywink** [comment]
- `items` table has `PRIMARY KEY (db_uuid, session, bundle, item_id)` -> unique
- `labels` table has `PRIMARY KEY (db_uuid, session, bundle, item_id, label_idx)` -> unique
