### ISSUE TITLE
convert_legacyEmuDB confused by paths with commas

### ISSUE THREAD

**Issue by stevecassidy** [IPS-LMU/emuR#109]
Old style Emu templates allow multiple extensions per path statement like this:

    path hlb,trg,lab 	children/*/labels
    path ssd,sfb,sf0    children/*/data

this causes problems in convert_legacyEmuDB, not sure where but it ends up generating a new database descriptor where the track definitions are missing the basePath attribute. This causes a later stage of the conversion to fall over. 

I got around this by converting to the long-form:

    path hlb	children/*/labels
    path trg	children/*/labels
    path lab	children/*/labels
  
    path ssd    children/*/data
    path sfb    children/*/data
    path sf0    children/*/data

However, there are many legacy databases in the wild with the above syntax.

Steve

**Comment by raphywink** [comment]
thanks for this! It is always those damn wild legacy databases that cause the problems :-).

@klausj could you maybe have a look at this? I think you know where to look better than I do...
