### ISSUE TITLE
Generated DBconfig from legacy database causes errors with webapp

### ISSUE THREAD

**Issue by stevecassidy** [IPS-LMU/emuR#110]
I'm converting an old database to use with emuR. I reported one issue with paths causing the conversion to fail. Having fixed that I have a working database that I am able to query in R.  However, when I try to use serve() to use the webapp, I get errors relating to the validity of the JSON configuration.  

I tried to fix some of these errors with reference to the validation messages. I removed basePath entries since they are not mentioned in the schema and I added a number of type properties that were missing from label and attribute definitions.  This allowed the webapp to load the database but it then hangs when trying to load a WAV file.  

I've put some files up at [https://gist.github.com/stevecassidy/f2e7596a34c2adc025b83f2ec19ebe20](url)

I can provide some sample data files on request.

**Comment by raphywink** [comment]
Oh dear! That children_DBconfig.json is absolutely full of invalid entries... sorry about that! No idea what went wrong there in the conversion...

Could you maybe send me a mini version of the legacyEmuDB (single utterance incl. all of it's track/hlb/label files should be enough) and a single bundle version of the converted emuDB? We'll have to carefully step though the conversion function with the debugger as there seem to be multiple problems/bugs in it.

**Comment by stevecassidy** [comment]
Hi Raphael,  well maybe this will shake out all of the bugs, it’s probably as complicated as any emu template.

Here are some samples of the original and converted data.

Cheers,

Steve

**Comment by klausj** [comment]
The legacy conversion code currently generates invalid DBconfig.json files in general.
It does not filter some transient properties anymore.
For example the invalid tarnsient property 'mediafileBasePathPattern' is written to the _DBconfig.json file.
emuR does not validate the DBconfig files, therefore it does not throw any errors and we overlooked the problem.

**Comment by klausj** [comment]
I've fixed the legacy conversion code.  The webapp accepts the converted DBconfig file now, but there is another problem with the example wav file sp1.1249.wav:
Chrome throws this error:
byte length of Int16Array should be a multiple of 2

The sp1.1249.wav file may have a strange header because it has an odd length of 283045 bytes.

**Comment by raphywink** [comment]
Just double checked and `sp1.1249.wav` seems to be a broken .wav file. It says it has a sample depth of 16 bits and then it says that there are 283001 bytes of data in the data block (== entry in `Subchunk2Size` position 40 in header) which our parser then can't view/cast as an Int16Array.

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/workers/wavParserWorkerClass.js#L217

**Comment by stevecassidy** [comment]
That was converted from SSD by a script I just whipped up - I’ll take a look again and fix it up.

Steve
—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 27 Apr 2016, at 1:15 AM, Raphael Winkelmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Just double checked and sp1.1249.wav seems to be a broken .wav file. It says it has a sample depth of 16 bits and then it says that there are 283001 bytes of data in the data block (== entry in Subchunk2Size position 40 in header) which our parser then can't view/cast as an Int16Array.

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/workers/wavParserWorkerClass.js#L217

**Comment by raphywink** [comment]
@stevecassidy I just remembered that I put together this script: https://gist.github.com/raphywink/e9bc1c1bde344c4d68d2 a while back to convert SSFF files containing audio (I think that was what files with the SSD extension was right?) to wav files using the wrassp package. Thought it might be useful for you...
