### ISSUE TITLE
load_emuDB with trailing backslash doesn't work on Windows

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/emuR#112]
If I pass a path with a trailing backslash to load_emuDB() on Windows, I get an error that the db directory doesn't exist. The same path without the trailing backslash works just fine.

On Linux, trailing slashes are no problem.

Don't know if this is much of an issue, though.

Thanks to Nora for pointing this out ;-)

**Comment by raphywink** [comment]
file.exist() seems to react differently on windows than it does on unixs:

```
file.exists(".") # true on windows and unixs
file.exists("./") # false on windows and true on unixs
```
