### ISSUE TITLE
feature request: copy_levelDefinition(emuDB,sourceLevel=,targetLevel=)

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#113]
This function could be useful to clone an existing level named  sourceLevel to a new identical 
instance named targetLevel, with exactly the same annotations and links.
Why is this a useful feature?
Suppose somebody used WebMASU to create an emuDB. Then he wants to correct the phonetic annotation using the EmuLabeller *but wants to keep the original MAUS annotation for cross-comparison* (e.g. to measure inter-labeler agreement).
Nowadays people out there do that with praat and of course they loose all hierarchical linkage after changing segments in  the copied level.

**Comment by raphywink** [comment]
Good idea! Should also be pretty simple to implement by simply calling `add_levelDefinition()`, copying the SQL entries and then calling the internal `rewrite_allAnnots()`function.

However I would probably add a third parameter to the function: `copyItems = TRUE/FALSE`. If set to TRUE all the items and their respecitve links are copied. If set to FALSO only the levelDefinition is copied.

What links do you think should be copied by default? All of them or just the links to the parent ITEMs (vs. to children also) or should it be optional parameter?

**Comment by florianschiel** [comment]
copyItems = TRUE/FALSE is a good feature.
I would prefer to copy everything exactly as it is; users can then decide to remove donwards links if necessary.
