### ISSUE TITLE
feature request: export_textgrid(emuDB=, levels= ...)

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#114]
Would be nice-to-have : flatten the emuDB hierarchy by the selected levels and create a TextGrid file for each bundle with a corresponding tier for each level (only those that can be linked to time information). If a selected level has elements that have no links to timing information ('floating ITEMs'), the elements in this level should be spread to equally sized options of the total speech signal.

**Comment by raphywink** [comment]
Just starting a test implementation for this now and I have a quick question: As bundle names are only unique within a session, should we export the TextGrid\_collection with the name of both the session and the bundle? So for example:

- `0000_ses/msajc003_bndl/msajc003.wav & _annot.json` -> `0000_msajc003.wav & .TextGrid``

or just use the bundle name:

- `0000_ses/msajc003_bndl/msajc003.wav & _annot.json` -> `msajc003.wav & .TextGrid``

the problem with the second alternative is that if two bundles with the name `msajc003` are present in 2 different sessions they would overwrite each other.

**Comment by florianschiel** [comment]
Could you keep just the bundle name, but export it into a subdir named 
after the session?

**Comment by raphywink** [comment]
Yep! That is the strategy I ended up going with anyway... a nice side-effect is that if you use `convert_TextGridCollection()` to re-create a emuDB from the exported TextGridCollection, the session structure is retained.

Should have a first version of this ready by tomorrow!

**Comment by raphywink** [comment]
implemented in version 0.1.9
