### ISSUE TITLE
feature request summary() : list attributeDefinitions?

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#122]
summary(emuDB) lists all level names, the number of assigned attributes per level, but not the names of the attributes.
You have to apply list_attributeDefinitions(levelName) to get that information.
However, most R users can't know about this function, while most know about summary().
Therefore often users are unaware of attributes in the emuDB.
Suggestion: extend the summary() output by a listing of all attribute names.

**Comment by raphywink** [comment]
Yep! I agree! Should be easy to implement...

**Comment by raphywink** [comment]
Just implementing this now and I have a quick question:

I think it would clutter the output of the summary function a bit too much if I add all the information of `list_attributeDefinitions(ae, "levelName")` to every level output. Currently `summary()` outputs the return value of `list_levelDefinitions(ae)`:

```
          name    type nrOfAttrDefs
1    Utterance    ITEM            1
2 Intonational    ITEM            1
3 Intermediate    ITEM            1
4         Word    ITEM            3
5     Syllable    ITEM            1
6      Phoneme    ITEM            1
7     Phonetic SEGMENT            1
8         Tone   EVENT            1
9         Foot    ITEM            1
```

how about we simply add an additional column to that output:

```
           name    type nrOfAttrDefs   attrDefNames
1     Utterance    ITEM            1    Utterance; 
2  Intonational    ITEM            1 Intonational; 
3  Intermediate    ITEM            1 Intermediate; 
4          Word    ITEM            3         Word; Text; Accent 
...
```

to reduce the clutter in `summary()` but have the level names???

**Comment by florianschiel** [comment]
Sounds fine to me.
