### ISSUE TITLE
autobuild_linkFromTimes() : bugs for writeToFS=F

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#126]
emuR_0.1.9.9014 

When setting the option writeToFS=F in autobuild_linkFromTimes() the function does not produce a consistent result.
See the following example:

> convert_TextGridCollection("CONVTMP","GlissandoNews",".",verbose=T)
INFO: Loading TextGridCollection containing 840 file pairs...
  |======================================================================| 100%
  INFO: Rewriting 840 _annot.json files to file system...
  |======================================================================| 100%
> gl.db = load_emuDB("GlissandoNews_emuDB")
INFO: Loading EMU database from GlissandoNews_emuDB... (840 bundles found)
  |======================================================================| 100%
> add_linkDefinition(gl.db,"MANY_TO_MANY","IntonationGroups","IntonationalPhrase")
> autobuild_linkFromTimes(gl.db,"IntonationGroups","IntonationalPhrase",convertSuperlevel=T,writeToFS=F)
> add_linkDefinition(gl.db,"MANY_TO_MANY","IntonationalPhrase","OrthographicTranscription")
> autobuild_linkFromTimes(gl.db,"IntonationalPhrase","OrthographicTranscription",convertSuperlevel=T,writeToFS=F)
> add_linkDefinition(gl.db,"MANY_TO_MANY","OrthographicTranscription","Syllables")
> autobuild_linkFromTimes(gl.db,"OrthographicTranscription","Syllables",convertSuperlevel=T,writeToFS=F)
> add_linkDefinition(gl.db,"MANY_TO_MANY","Syllables","PhoneticTranscription")
> autobuild_linkFromTimes(gl.db,"Syllables","PhoneticTranscription",convertSuperlevel=T)
  INFO: Rewriting 840 _annot.json files to file system...
  |======================================================================| 100%> 
> 
> summary(gl.db)
Name:    GlissandoNews 
UUID:    ecfc8bbe-d794-4a37-8142-88705e5b6af2 
Directory:       /vdata/BAS/GLISSANDO/GlissandoNews_emuDB 
Session count: 24 
Bundle count: 840 
Annotation item count:  1687938 
Label count:  1687938 
Link count:  1112553 

Database configuration:

SSFF track definitions:
NULL

Level definitions:
                       name    type nrOfAttrDefs               attrDefNames
1 OrthographicTranscription SEGMENT            1 OrthographicTranscription;
2     PhoneticTranscription SEGMENT            1     PhoneticTranscription;
3                 Syllables    ITEM            1                 Syllables;
4        IntonationalPhrase SEGMENT            1        IntonationalPhrase;
5          IntonationGroups SEGMENT            1          IntonationGroups;
6 Syllables-autobuildBackup SEGMENT            1 Syllables-autobuildBackup;

Link definitions:
          type            superlevelName              sublevelName
1 MANY_TO_MANY          IntonationGroups        IntonationalPhrase
2 MANY_TO_MANY        IntonationalPhrase OrthographicTranscription
3 MANY_TO_MANY OrthographicTranscription                 Syllables
4 MANY_TO_MANY                 Syllables     PhoneticTranscription

Only the last autobuild worked as expected: the level Syllables was transformed into type ITEM and a backup level was created. All the other levels (where autobuild was used with writeToFS=F) are still of type SEGMENT and no backup level was created. At least that is what the function wrote into the DBConfig file and shows in summary(). 
In fact the *_annot.json files in the FS contain partly correct output: all levels except PhoneticTranscription were transformed in to type ITEM and all the links have been set correctly. However, only the level Syllables has been copied before transformation into a backup level.
So, there are basically two problems when using writeToFS=F :
1. No Backup level is created, but the Superlevel is transformed into type ITEM.
2. The DBConfig defines the Superlevel still as SEGMENT although it has been transformed to ITEM in the FS.

**Comment by raphywink** [comment]
This probably has to do with the `writeToFS` flag also affecting if the DBconfig is written to disc or not. Still have to wait for the tests to pass but I think that'll fix the problem (will close issue if that is the case). I also renamed the `writeToFS` flag to `rewriteAllAnnots` as that is what it triggers from now on.

Just to shortly explain what happened:

All the `autobuild_linkFromTimes` calls probably worked correctly. The only thing that wasn't updated correctly was the DBconfig (it's content affects the output of `summary()`). If I do this:

```
> sqlite3 GlissandoNews_emuDBcache.sqlite
SELECT DISTINCT level, type from items;
OrthographicTranscription|ITEM
PhoneticTranscription|SEGMENT
Syllables|ITEM
IntonationalPhrase|ITEM
IntonationGroups|ITEM
IntonationGroups-autobuildBackup|SEGMENT
IntonationalPhrase-autobuildBackup|SEGMENT
OrthographicTranscription-autobuildBackup|SEGMENT
Syllables-autobuildBackup|SEGMENT
````
it displays all the levels (including their backups). So the content of the emuDBcache is correct.  However the `rewrite_allAnnots()` function only rewrites the levels that it can find in the DBconfig. So the first calls to `autobuild_linkFromTimes` are not reflected in the DBconfig.
