### ISSUE TITLE
Feature request: export_BPFCollection()

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#128]
Analog to export_TextGridCollection() his function exports (parts) of a hierarchical emuDB into BPF files (one *.par per bundle). This would be very useful for people like me that have a lot of software working on BPF input.

Features:
The reference level must be set by the user (e.g. ref='Word'), then all Attributes or one-to-one linked levels are transformed into BPF type 1 tiers, and all one-to-many or many-to-many linked levels from the reference level are transformed into BPF type 4 (SEGMENT) and 5 (EVENT).
The function further needs a mapping from emuDB level/attribute names to BPF standard tier names, e.g. 'Word' -> 'ORT', 'phonetic' -> 'SAP' etc.
(Theoretically, other levels (SEGMENT/EVENT) that are not linked to the reference level could be transformed into BPF type 2 and 3 as well, but this would be just a nice-to-have, not really essential.)

**Comment by raphywink** [comment]
implemented as of version 0.2.3
