### ISSUE TITLE
re-writing to FS after an autobuild() leaves DBConfig buggy

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#129]
Using emuR_0.1.9.9016

When using autobuild_linkFromTimes() with the options convertSuperlevel=T,rewriteAllAnnots=T
the function correctly changes the superlevel from SEGMENT to ITEM, but fails to delete the superlevel from the "levelCanvases" array.
Since an ITEM level cannot be shown as a canvas (which by the way is a pitty), this causes an error the next time the emuDB is loaded or served to the EmuWebApp.

**Comment by raphywink** [comment]
`autobuild_linkFromTimes()` updates the DBconfig to not display the converted levels as time levels in the EMU-webApp
