### ISSUE TITLE
Implement function to remove links

### ISSUE THREAD

**Issue by klausj** [IPS-LMU/emuR#131]
Users tried to remove links with function remove_linkDefinition, but this function only removes the defintion and only if no links of this definition exist.
So I think we should implement a function like this:
remove_links(emuDBhandle, superlevelName, sublevelName)

To avoid unintentional removal, the function should request confirmation from the user before actully removing the links.

**Comment by raphywink** [comment]
`remove_linkDefinition()` implements a `force` parameter as of version 0.2.2 that deletes all links associated with that link definition.
