### ISSUE TITLE
sequence query: concatenated label in wrong order when sessionPattern is given

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/emuR#140]
We processed a database with MAUS and then manually (using EMU-webApp) added a number of segments labeled "rel", which is short for "release". All of these segments are between a stop label and a vowel label.

Now if I compare these two queries:

```R
sl.wrong = query(db, "[phonetic=rel -> phonetic = i]", sessionPattern = "0001.*")
sl.right = query(db, "[phonetic=rel -> phonetic = i]")
```

All I should be getting as a label in my segment lists is "rel->i". This works as expected for sl.right, however not so for sl.wrong:

```R
> summary(sl.right)
segment  list from database:  Finnisch 
query was:  [phonetic=rel -> phonetic = i] 
 with 156 segments

Segment distribution:

rel->i
   156 


> summary(sl.wrong)
segment  list from database:  Finnisch 
query was:  [phonetic=rel -> phonetic = i] 
 with 12 segments

Segment distribution:

i->rel 
    12
```

For some reason the label concatenation gets screwed. Initially I suspected it has to do with the fact that the rel's were added later and are thus stored at the end of the items array - but then I discovered the relation with sessionPattern and now I am totally confused.

**Comment by raphywink** [comment]
Could you maybe retry this on the emuDB you where working with. I think this might have been fixed with f82eb60f0a4a7c8d

**Comment by MJochim** [comment]
Does not appear to be fixed in 1.0.0 :(. I am still getting i->rel instead of rel->i.

**Comment by raphywink** [comment]
WTF? Just also retried it... and it is busted again? Hä?

**Comment by raphywink** [comment]
god I love SQL
