### ISSUE TITLE
rename_attributeDefinition only works when anagestConfig is defined

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/emuR#145]
In the database configuration, a level definition *may* include an object named "anagestConfig", which in turn *must* include a string attribute named "autoLinkLevelname".

The function ```rename_attributeDefinition()``` looks for the original name (which is to be changed) in several places, amongst them anagestConfig.autoLinkLevelName. If anagestConfig is not defined (which is a valid state), the function errors out. A missing definition in one of the level definitions already causes this error.

**Comment by raphywink** [comment]
I couldn't reproduce the error. `rename_attributeDefinition` on a level that anagestConfig.autoLinkLevelName refers to works and on the level containing the anagestConfig it also works. Please reopen if I missed something
