### ISSUE TITLE
Does encoding="UTF-8" have the intended effect?

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/emuR#154]
In order for Windows/R not to re-encode file contents, we started using ```useBytes=T``` when calling writeLines() (see 5d29c6e). This parameter does not exist for readLines(). In #153 we have been discussing whether ```encoding="UTF-8"``` is a sufficient replacement. Somebody, please confirm ;-).

**Comment by raphywink** [comment]
Now moved to using `readr::` functions to ensure correct encodings across platforms. Everything else just doesn't work (especially under windows).  `useBytes=T` does work, however in many cases the reencoding happens elsewhere. See also #188 #187
