### ISSUE TITLE
Do/Will emuDB support nested sessions?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#165]
Unless I am misstaken you can only have one layer of _sess directories, right? At least I have not been able to get it to work:

```
> dbPath = file.path(tempdir(), 'fromScratchDB_emuDB')
> dbHandle = load_emuDB(dbPath, verbose = F)
> print(dbHandle)
[1] "<emuDBhandle> (dbName = 'fromScratchDB', basePath = '/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB')"
> list_sessions(dbHandle)
  name
1    1
2    2
> list.dirs(path="/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB",recursive = TRUE)
[1] "/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB"            
[2] "/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB/1_ses"      
[3] "/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB/2_ses"      
[4] "/private/var/folders/_8/_tsst82j257bv9hk57dgxgt00000gr/T/RtmpjusJKh/fromScratchDB_emuDB/2_ses/3_ses"
```

The reason why I am asking this is that I think for any project that involves a series of followups for a single participant, and different tasks that you want to keep separate, then will seem like a rather big limitation of the system. Both the task and time/date information will then be encoded in the file name of the bundle directories, which I think will be a bit messy. 

And even more so if you hav clinical project where you may have on/off medication recordings performed on the same day. 

So, in essence - will nesting of _ses directories be allowed, and useful somehow in searching?

**Comment by raphywink** [comment]
Yep! Currently the emuDB format doesn't support nested session structures. For information such as time/date values I would recommend using the strategy I wrote about here: https://github.com/IPS-LMU/emuR/issues/161 that also includes things such as on/off medication and so on. However, I do see a benefit in allowing nested session folders for better file / bundle Organization (simple things such as this folder contains all male speakers... this sub-folder contains each recording of patientX and so on). I would have to look into how difficult it would be to simply allow for session folder chains to be used as session identifiers within the system (bla_ses treated the same as bla_ses/bli_ses/blup_ses as a session identifier). Unfortunately, I won't get around to this any time soon (maybe in a few weeks/months though). Will get back to you... (please leave the issue open so I don't forget)

**Comment by samgregory** [comment]
Hey @FredrikKarlssonSpeech - have you found that using metadata gets around this limitation of the emuR structure?
Can we / should we close this?

**Comment by FredrikKarlssonSpeech** [comment]
@samgregory Yes. With a metadata aware database system, I think the need of an ability to have nested sessions are far less urgent.
