### ISSUE TITLE
emu can't read certain WAV files

### ISSUE THREAD

**Issue by jeliasulloa** [IPS-LMU/emuR#166]
Hi, I'm not sure if this is the right place to report this sort of bugs but I have a bunch of WAV files recorded with a Zoom H4n and an Edirol (in both cases, the audio files were created with the same settings: WAV PCM, mono, 44100Hz, 16 bit). When I input the command serve(dbName) in emuR, the program can open the WAV files recorded with the Edirol but for those recorded with the Zoom H4n, I obtain an error message that says "Error parsing wav file: Wav read error: Subchunk1Size not 16, 18 or 40 but 858". Feel free to get in contact with me if you'd like a sample of my files. best, Jose.

**Comment by raphywink** [comment]
Hi Jose,
that is interessting. Could you send me such a file (either here or to my Uni email adress which you can find here: http://www.en.phonetik.uni-muenchen.de/people/staff/winkelmann_raphael/index.html)? Would be interessting to see what Zoom uses the extra 842 bytes for :-). I could probably fairly easily fix the problem in our wav parser (which actually only needs to look for the sample rate and bit depth).
Greetings from Munich
Raphael

**Comment by raphywink** [comment]
I just fixed this https://github.com/IPS-LMU/EMU-webApp/commit/c09f74f38cf121fcb3ca6d2aab86a401d67f9c2e. The fix will be in the next release (will wait until a few more features/bug fixes build up before deploying a new version). Just as a quick heads up: this was an issue with the EMU-webApp not with emuR, so the EMU-webApp repo would have been the correct place to issue this issue. No biggy though ;-)

**Comment by jeliasulloa** [comment]
Thanks! I'm looking forward to trying the new version.

best,

Jose
