### ISSUE TITLE
Description of SQL schema?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#167]
The R part of the bundle of packages that you are putting together here to support the analysis of speech data is something that more people would actually be able to easily contribute to. I have an agnostic position when it comes to matters that relate to GUI and web services, but core functionality is of interest. However, the R code related to database features is very much dependent on you understanding the schema and what is stored where, so I would suggest that putting effort now into describing the schema would allow more people to contribute, if that is desired.

**Comment by raphywink** [comment]
The SQL schema will also be described in the upcoming EMU-SDMS manual. I am working as hard as possible to get it done but unfortunately my resources are currently limited (hopefully only a few weeks to go...). However, the core relational cache (= SQLite DB) structure can easily be examined by looking at the connection:

```r
ae = load_emuDB("~/Desktop/emuR_demoData/ae_emuDB/")
DBI::dbListTables(ae$connection) # list all tables
DBI::dbListFields(ae$connection, "items") # list columns in items table
```

Their definitions can be found here: https://github.com/IPS-LMU/emuR/blob/master/R/emuR-database.R#L27

The many many temporary tables that are used throughout the querying process (to mainly store intermediate results) are an entirely different beast though (and also waaaaaay more complicated to describe). To get an idea of how they work I would suggest stepping through the source code of a simple query using a debugger. If you want to understand how to build a database using the cache, I would suggest looking at one of our conversion functions (e.g. https://github.com/IPS-LMU/emuR/blob/master/R/emuR-convert_txtCollection.R).

**Comment by raphywink** [comment]
Just FYI: The EMU-SDMS manual will also contain some information regarding the SQL schema.
