### ISSUE TITLE
get_trackdata() : warning on emu DB with inhomogeneous sampling rates

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#168]
Feature request: if get_trackdata() is called on a loaded emu DB with inhomogeneous sampling rates, it would be nice to warn the user about it, because some analyses will deliver results depending on the sampling rate of the signal.
Example: a user wants to analyse the 1st moment of spectral power. If signal file A has a sampling rate of 16000, signal B has 44100, the results are not comparable.

**Comment by raphywink** [comment]
https://github.com/IPS-LMU/emuR/blob/master/R/emuR-get_trackdata.R#L178 implements this
