### ISSUE TITLE
add_ssffTrackDefinition (or actually list_files) finding track files incorrectly

### ISSUE THREAD

**Issue by dargosch** [IPS-LMU/emuR#170]
```
> list_ssffTrackDefinitions(ddk)
      name columnName fileExtension
1 formants         fm           fms
> add_ssffTrackDefinition(emuDBhandle = ddk,
+                         name = "pitch",
+                         columnName = "f0",
+                         fileExtension = "f0",onTheFlyFunctionName = "f0ana")
There are files present in 'DDK' that have the file extention 'f0'! Continuing will overwrite these files! Do you wish to proceed? (y/n) n
```

However, there are no .f0 files in the database. 

```
> list.files(ddk$basePath,pattern = ".*[.]f0$",recursive = TRUE)
character(0)
> list.files(ddk$basePath,pattern = ".*[.]f0",recursive = TRUE)
character(0)
```
when 
There are some files that fulfill less stricture queries 
```
list.files(ddk$basePath,pattern = "*.f0",recursive = TRUE)
[1] 54
```
I tracked down the issue, and it is in list_files().
I suggest that code lines like this:

`fps = list.files(file.path(emuDBhandle$basePath, paste0(bndls[i,]$session, "_ses"), paste0(bndls[i,]$name, "_bndl")), pattern = fileExtension)
`

should really be made sure that they have a restrictive pattern, like so

`   fps = list.files(file.path(emuDBhandle$basePath, paste0(bndls[i,]$session, "_ses"), paste0(bndls[i,]$name, "_bndl")), pattern = paste0(".*[.]",fileExtension,"$"))
`
or something like that.

**Comment by raphywink** [comment]
Thanks for this! Forgetting the "$" in the pattern argument must have been an oversight on my side. Fix should be up in a sec (unit tests are still running).
