### ISSUE TITLE
Failed calls to add_ssffTrackDefinition needs manual cleanup

### ISSUE THREAD

**Issue by dargosch** [IPS-LMU/emuR#171]
I think there should be some cleanup if adding of track definitions with a onthefly computation function fails for whatever reason.
```
> list_ssffTrackDefinitions(ddk)
      name columnName fileExtension
1 formants         fm           fms
> add_ssffTrackDefinition(emuDBhandle = ddk,
+                         name = "pitch",
+                         columnName = "f0",
+                         fileExtension = "f0",onTheFlyFunctionName = "f0ana")
There are files present in 'DDK' that have the file extention 'f0'! Continuing will overwrite these files! Do you wish to proceed? (y/n) n
> list_ssffTrackDefinitions(ddk)
      name columnName fileExtension
1 formants         fm           fms
2    pitch         f0            f0
```

At this point you need to then manually remove_ the track definitions, which seems not the way it should be.

Also, if I answer 'y' to the question above, nothing happens. I would have expected .f0 files to be computed, and then overwriting existing .f0 files in bundles.
But, this may be related to the other issue I just posted.

**Comment by raphywink** [comment]
Could you maybe send me a tiny emuDB (single bundle is plenty) so I could reproduce the problem? That would save me having to rename a bunch of bundles until I can reproduce the problem. I am guessing that there are 2 problems here:
1.) The issue that should now be fixed (see #170)... probably a file matching the RegEx ".*f0.*"
2.) cleaning up after fails/user interrupts: Catching the explicit `n` user input and cleaning up should be easily doable (I will look at this straight away... I also think this is a good idea). However, error handling in R is not as you would expect (in my humble opinion it is barely usable). So in other words, raising an exception when something goes wrong then catching that exception to then do some cleanup is a massive hassle in R. Although I would be all for doing this, I don't think implementing "error catching" around emuDB manipulation functions is currently a feasible option.
