### ISSUE TITLE
Not able to create a f0 track 

### ISSUE THREAD

**Issue by dargosch** [IPS-LMU/emuR#172]
I've been able to compute formant data using 'forest' and an RMS amplitude track using 'rms', but my attempts at creating a pitch track 

```
> add_ssffTrackDefinition(emuDBhandle = ddk,
+                         name = "pitch",
+                         columnName = "pitch",
+                         fileExtension = "pitch",onTheFlyFunctionName = "ksvf0")
Error in get(fun, mode = "function", envir = parent.frame()) : 
  object 'ksvf0' of mode 'function' was not found
> mode(ksvF0)
[1] "function"
> add_ssffTrackDefinition(emuDBhandle = ddk,
+                         name = "pitch",
+                         columnName = "pitch",
+                         fileExtension = "pitch",onTheFlyFunctionName = "mhsf0")
Error in get(fun, mode = "function", envir = parent.frame()) : 
  object 'mhsf0' of mode 'function' was not found
> mode(mhsF0)
[1] "function"
```
So, the functions appear to be there, but something is still not working correctly.

**Comment by raphywink** [comment]
You have a small typo in the function name in the `onTheFlyFunctionName` parameter: `"mhsf0"` vs. `"mhsF0"` (with a capital F). You will also have to reset the `columnName` parameter to "F0" as `mhsF0` does not produce a column/track with the name "pitch" (see the output of `wrassp::wrasspOutputInfos$ksvF0` to see the produced tracks/columns)

**Comment by dargosch** [comment]
Yes, that was for sure the problem. I am generating pitch contours now. Confusingly enough, the **mhsF0** functions _does_ have a column 'pitch', but **ksvF0** does not. For this function the column is 'F0'. 

```
> wrassp::wrasspOutputInfos
...
$ksvF0
$ksvF0$ext
[1] "f0"

$ksvF0$tracks
[1] "F0"

$ksvF0$outputType
[1] "SSFF"


$mhsF0
$mhsF0$ext
[1] "pit"

$mhsF0$tracks
[1] "pitch"

$mhsF0$outputType
[1] "SSFF"
```
 
Of course this is all related to wrassp, but the situations is a bit confusing. It does not excuse my typo, but still.. I think this is a point where people will make mistakes (not just me).
