### ISSUE TITLE
Suggestions related to label_num

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#174]
I was confused by the presence of a 'label_num' function among the exported ones while searching for the 'label' function. The documentation is not informative, and looking at the code it was not really obvious at first what the function does.

While waiting for a script to finish I thought I'd try to figure it out. 
I am not entirely sure, but my quick testing suggests that 'label_num' could be rewritten a bit.
Maybe not for the better for readers of the code that are not familiar with how factors work in R, but they appear equivalent, and the one that uses the built in functionality of R is faster.

```
#The original implementation
label_num <- function (labs) 
{
    qq <- unique(labs)
    nums <- c(1:length(qq))
    for (j in 1:length(qq)) {
        temp <- labs == qq[j]
        labs[temp] <- nums[j]
    }
    as.numeric(labs)
}

label_num2 <- function (labs) {
  return(as.numeric(factor(mytest,levels=unique(labs))))
}
# Indication that the output is the same?
> for(i in 1:100){ sample(LETTERS,22,TRUE) -> mytest; if(! all.equal(label_num(mytest), label_num2(mytest))){cat("Not identical!")} }
> 

library(microbenchmark)
> microbenchmark(label_num(mytest),label_num2(mytest))
Unit: microseconds
               expr    min      lq     mean  median      uq     max neval cld
  label_num(mytest) 24.827 26.0285 45.82241 29.0125 36.3115 321.596   100   b
 label_num2(mytest) 13.913 15.8005 26.03111 17.7750 28.6870 115.345   100  a 
```

I think this function may not be indented for internal use only, and should be not exported. Please also use my new implementation if you want to.

**Comment by raphywink** [comment]
added deprication notice in help page
