### ISSUE TITLE
Could the "linkDefinition" concept be reconsidered

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#181]
While "linkDefinitions" are strictly speaking what is being managed by remove_linkDefinition, add_linkDefinition and list_linkDefinition functions, I suggest that the name should be reconsidered.
I fear that this is a crucial point where new users with preexisting data will be deterred from learning more about the EmuDB system. I will try to illustrate why using the example in the help pages:

```
create_emuRdemoData(dir = tempdir())
convert_TextGridCollection(dir=file.path(tempdir(),"emuR_demoData","TextGrid_collection"),dbName="TG",targetDir = file.path(tempdir(),"emuR_demoData"))
myTGcolDB <- load_emuDB(databaseDir = file.path(tempdir(),"emuR_demoData","TG_emuDB"))
add_linkDefinition(emuDBhandle = myTGcolDB,type = "ONE_TO_MANY",superlevelName = "Phoneme", sublevelName = "Phonetic")
> query(myTGcolDB,"[Phonetic=~.* ^ Phoneme=k]")
segment  list from database:  TG 
query was:  [Phonetic=~.* ^ Phoneme=k] 
[1] labels  start   end     session bundle  level   type   
<0 rows> (or 0-length row.names)
```
at this point I think I would just give up and conclude that I once more have stumbled upon  a collection of scripts that promises more than what they deliver.

Of course, this will work

```
autobuild_linkFromTimes(myTGcolDB,"Phoneme","Phonetic")
summary(query(myTGcolDB,"[Phonetic=~.* ^ Phoneme=k]"))
segment  list from database:  TG 
query was:  [Phonetic=~.* ^ Phoneme=k] 
 with 15 segments

Segment distribution:

H k 
7 8
```

but to be honest I think I would have assumed that defining a link between two levels in an existing data set would also set up the links. And I think one of the issues may be found in the "linkDefinition" concept. Is it really a definition of links? Perhaps it is better described as a definition of the relationship between two levels? 

I am not convinced that having linkDefinitions between levels and links between labels is a good idea.

**Comment by raphywink** [comment]
Just going through old issues (I must have missed this one and a few others... sorry about that): I don't really agree with this as the entire concept of an emuDB is having "definitions" that say something **can** exist in an emuDB but not that it is there or created for you. If you create a levelDefinition you create the possibility of creating annotation items in that level but you don't fully automatically annotate the speech database. Same is true for linkDefinitions: you create the possiblity of a certain type of hierachical relationshit... not the relationships themselves. As this is an old issue I'll close it... reopen if you disagree/think this needs more discussion...
