### ISSUE TITLE
EMU web-App save changes special characters

### ISSUE THREAD

**Issue by colan101** [IPS-LMU/emuR#188]
As already mentioned in issue #187 , whenever I use the "save" option in the EMU web-app, all special characters in the JSON file are encoded wrong. For example: "ʃ" was replaced with "Êƒ" and "ú" was replaced with "Ãº".

I'm using R 3.4.4 and RStudio on Windows 10 and Firefox for the EMU web-app.

As requested, this is the output of devtools::session_info():

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2018-03-28                  

Packages ---------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                       
 base       * 3.4.4      2018-03-15 local                        
 bit          1.1-12     2014-04-09 CRAN (R 3.4.1)               
 bit64        0.9-7      2017-05-08 CRAN (R 3.4.1)               
 blob         1.1.0      2017-06-17 CRAN (R 3.4.4)               
 compiler     3.4.4      2018-03-15 local                        
 datasets   * 3.4.4      2018-03-15 local                        
 DBI          0.8        2018-03-02 CRAN (R 3.4.4)               
 devtools   * 1.13.5     2018-02-18 CRAN (R 3.4.3)               
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)               
 emuR       * 0.2.3.9020 2018-03-28 Github (IPS-LMU/emuR@b97b5cb)
 graphics   * 3.4.4      2018-03-15 local                        
 grDevices  * 3.4.4      2018-03-15 local                        
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.4)               
 magrittr     1.5        2014-11-22 CRAN (R 3.4.4)               
 MASS         7.3-49     2018-02-23 CRAN (R 3.4.4)               
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.4)               
 methods    * 3.4.4      2018-03-15 local                        
 pillar       1.2.1      2018-02-27 CRAN (R 3.4.4)               
 Rcpp         0.12.16    2018-03-13 CRAN (R 3.4.4)               
 rlang        0.2.0      2018-02-20 CRAN (R 3.4.4)               
 RSQLite    * 2.0        2017-06-19 CRAN (R 3.4.4)               
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.4)               
 stats      * 3.4.4      2018-03-15 local                        
 stringi      1.1.7      2018-03-12 CRAN (R 3.4.4)               
 stringr      1.3.0      2018-02-19 CRAN (R 3.4.4)               
 tibble       1.4.2      2018-01-22 CRAN (R 3.4.4)               
 tools        3.4.4      2018-03-15 local                        
 utils      * 3.4.4      2018-03-15 local                        
 uuid         0.1-2      2015-07-28 CRAN (R 3.4.1)               
 withr        2.1.2      2018-03-15 CRAN (R 3.4.4)               
 wrassp       0.1.6      2018-01-19 CRAN (R 3.4.4)               
 yaml         2.1.18     2018-03-08 CRAN (R 3.4.4)

Please tell me if you need any further information.

**Comment by raphywink** [comment]
I was just able to reproduce the problem on my Windows 10 machine. Hopefully it won't be too difficult to fix...

**Comment by colan101** [comment]
Thank you very much, everything is working fine now!
