### ISSUE TITLE
Databases with heterogeneous sampling rates should be handled without issues

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#190]
Databases with varying sample rates in the sound files should just he handled gracefully. 

Alternatively, there should be a way to fix the issue in a very simple way. If not in any other way, resampling at import of files. I think it is not good if the user discovers as late as when derived files have already been generated that the database cannot be used due to (for instance, like in my case below) there being a mix of 48 and 44.1 kHz sampled sound files in the database. 

```
> load_emuDB("DDKDB_emuDB/") -> ddk
INFO: Checking if cache needs update for 1 sessionsand  333 bundles ...
INFO: Performing precheck and calculating checksums (== MD5 sums) for _annot.json files ...
INFO: Nothing to update!
> oneSegment <- query(ddk, "[CV =~.* ^ Num(Syllable,CV) ==1]") 
> get_trackdata(ddk,oneSegment,"pitch") -> oneSegmentPitch
Error in get_trackdata(ddk, oneSegment, "pitch") : 
  The emusegs/emuRsegs object passed in refers to bundles with in-homogeneous sampling rates in their audio files! Here is a list of all refered to bundles incl. their sampling rate: 
    session                                              name
1      PDNC            10_08_c9065d43d3212757971834bf4d3d067c
2      PDNC          100_288_89b28128373b4f2c1dbd7154c23b7105
3      PDNC 101_066666666667_f91e96438ac50475f72157eec428ce67
4      PDNC           101_28_8c130e18a811f94ff48710a8981a9677
5      PDNC 101_436598639456_06f4dcc7b980fb58577597ccbee5ce2e
6      PDNC 101_450666666667_9d7ef21efb3b109c2dc6427d6bf10571
7      PDNC          101_696_d8b0798aeeb535e19f2ddbb92a9fb003
8      PDNC          101_696_f2312069a1f637104bd3ee0973ba3711
9      PDNC           101_92_b07a6727e544c033d6891c499475ca69
10     PDNC       101_992125_2c2a23b6b2d18c814a26de44e0c2fd46
11     PDNC          102_592_ebb216bcd3bf50a8da9ccb70cb36a359
12     PDNC 103_786666666667_79fe1e213ec1c1d73a5ab0f768d7e7d7
13
```

**Comment by FredrikKarlssonSpeech** [comment]
Looking at the code its easy to see where the check of sampling frequencies is performed.

https://github.com/IPS-LMU/emuR/blob/5668df653b457774cfce244b79eea783369474cc/R/emuR-get_trackdata.R#L173-L189

Some substantial work has been put into implementing this check, so there is surely a good reason for it. But, I cannot understand what that is and for me it now looks like a good option to simply remove this check in the code I need to use to enable emuR to function again. 

The signals have already been generated when you run the command so the signal processing cannot be the issue. What is the issue that is fixed by this check?

**Comment by raphywink** [comment]
I disagree! As I have stated before certain (especially spectral) analysis is affected by the sample rate and will introduce undesired side effects that people are not aware of. Think e.g. Nyquist frequency effect on high frequencies with low sample rates:

- 16000 Hz SR -> Nyquist frequ. = 8000Hz
- 8000 Hz SR -> Nyquist  frequ. = 4000Hz

now if you analyse the high frequency portion of the spectrogram (e.g. 3000 - 5000 Hz) you will get an effect of sample rate... nothing else...  I am willing to consider an additional parameter that switches off the checks though. But then people really have to know what they are doing regarding signal processing (which unfortunately some people don't). In general, I consider it bad practice to build databases with variable sample rates...

**Comment by FredrikKarlssonSpeech** [comment]
Yes, you are right of course. With regards to spectral data, combined with with low sampling rates. 
But, right now everyone is prevented from accessing data from even a derived track that has already been computed due to this code.

And, in my case the offensive sample rates that prevents me from getting data are the ca 30% of filed with a 48kHz and not the 44.1kHz that are used in the majority of files in the database. Basically some files come from DAT recordings and some were made using a computer at a sampling frequency that we considered adequate at the time.

Would it be an acceptable solution to issue a warning and not a stop if sample rates are really all above 44kHz or a cutoff that could have a reasonable default value?

**Comment by raphywink** [comment]
Changed the `stop()` to a `warning()`. If people ignore the warning (which they will) it is their own damn fault...

**Comment by FredrikKarlssonSpeech** [comment]
Thank you!
