### ISSUE TITLE
items not linked to time level are dropped when calcTimes==T

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/emuR#193]
@raphywink I found out why my query() did not return the programmatically inserted items. The reason is that they are not linked to any items on a time level and thus carry no implicit time information. As long as calcTimes is TRUE (which is the default), unlinked items are dropped in ```convert_queryResultToEmuRsegs```. When I set calcTimes to FALSE, I get what I expected – all old and all new items. Is this behavior intended? Shouldn't the items be included and have ```NA``` times?

**Comment by raphywink** [comment]
Yes that behaviour is intended. `calcTimes = T` basically does the same thing as `^` with the child level containing time (not "basically": https://github.com/IPS-LMU/emuR/blob/master/R/emuR-create_seglists.R#L151 it actually uses the same internal function :-)).

**Comment by MJochim** [comment]
Okay I see. Does that mean that in legacy emu (and/or in the current version before the advent of the calcTimes option), unlinked items could never be returned in a query?

**Comment by raphywink** [comment]
that is correct simply because you can't calculate the times for something that isn't there

**Comment by MJochim** [comment]
I think then that this should go in the documentation of the ```calcTimes``` parameter.

**Comment by raphywink** [comment]
rewrite of EQL now preserves these elements but returns NA values for their times
