### ISSUE TITLE
mel.spectral performance issue

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/emuR#2]
The `rbind` in `mel.spectral` is causing performance issues on large data sets. Try using preallocation to remove the constant allocation in the loop

**Comment by florianschiel** [comment]
Also I'd like to suggest that mel() returns a class 'numeric spectral' for input of class 'numeric spectral' and not 'matrix spectral' as it is now the case.
Further (although this regards not the mel() itself but rather the class 'spectral'), it would be nice if the index function for 'spectral' ([.spectral()) does not return the last element of a vector etc., if the index is out-of-bounds. Rather (as with other index functions in R) it should return an error 'index out of bounds' or at least a NA.

**Comment by raphywink** [comment]
I am going to close this issue as I think we should focus our efforts on the new `emuRtrackdata` object to perform these calculations at a decent speed. If people want to use the old `trackdata` object it is just going to be as slow and quirky it always was :-)
