### ISSUE TITLE
when calling runBASwebservice_all() I get the error "Connection timed out after 10001 milliseconds"

### ISSUE THREAD

**Issue by martonbartok** [IPS-LMU/emuR#205]
I've been using this function for forced alignment in the past month several times, but in the last few days I always get this connection error. My internet connection has the same speed than before, so I've no idea what could be the problem.

**Comment by NPoe** [comment]
Hi Marton, 
The BAS webservices have been offline since Thursday, 13 September, due to planned electricity work. As far as I know, servers are due to reboot tomorrow, 17 September. Let us know if your issues persist beyond that time.

**Comment by raphywink** [comment]
Just tried:

```{r}
convert_txtCollection(dbName = "txtCol",sourceDir = "~/Desktop/emuR_demoData/txt_collection/", targetDir = "~/Desktop/")
db = load_emuDB("~/Desktop/txtCol_emuDB/")
runBASwebservice_all(db, transcriptionAttributeDefinitionName = "transcription", language = "eng-AU")
```

and everything seems to be working again (servers have been up since approx. 8-9 o'clock this morning). Sorry for any inconvenience this might have caused you.

**Comment by martonbartok** [comment]
thanks for the info, indeed, it's working! Thanks for the great package!

**Comment by raphywink** [comment]
Perfect! Glad you like it ;-)
