### ISSUE TITLE
Search annotations in EMU-webApp

### ISSUE THREAD

**Issue by PeterGilles** [IPS-LMU/emuR#208]
I see there is a search option in the webApp to search annotations. Is it also possible to extend this search to all files in the database? E.g. to generate a list of all recordings containing a certain word or sound combination and display these subselected files only list on the left side.

**Comment by raphywink** [comment]
Yes this is possible. Simply use the powerful query mechanics provided by emuR: 

- https://ips-lmu.github.io/The-EMU-SDMS-Manual/chap-querysys.html
- https://ips-lmu.github.io/The-EMU-SDMS-Manual/app-chap-eql.html

and pass the resulting object into the `serve(..., seglist = XXX)` function
