### ISSUE TITLE
convert_BPFCollection() : level 'bundle' contains no values

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#209]
I'm not sure whether this is a bug or a feature: when using convert_BPFCollection() to import a BAS Partitur Format corpus, the resulting emuDB had a root node level 'bundle' (with many attributes) that is always empty (i.e. value is the empty string). I was expecting the bundle name here as value, so that I can use it in queries. If this has a reason and is supposed to be that way, please just close this issue.

**Comment by raphywink** [comment]
I think the idea was to have a single bundle root node on a level called `bundle` that contains all the meta infos. As an attribute that has the same name as the level (i.e. `bundle` for this level) has to be present, it is simply left empty (bundle names can however be specified using the `bundlePattern` argument of `query()` ). Placing the bundle name into that attribute would def. be possible, however it would be redundant information.
