### ISSUE TITLE
Evaluation error in rename_bundles() function

### ISSUE THREAD

**Issue by trblslp** [IPS-LMU/emuR#218]
I have a bundles object which looks as follows.

session<chr> | name<chr> | name_new<chr> |   |  
-- | -- | -- | -- | --
0000 | sl_rowIdx_1 | Hilda_14July19_init_heavy_phra_init_balbara_1 |   |  
0000 | sl_rowIdx_10 | Hilda_14July19_init_heavy_phra_init_balbara_2 |   |  
0000 | sl_rowIdx_100 | Hilda_14July19_init_heavy_phra_init_balbara_3 |   |  
0000 | sl_rowIdx_101 | Hilda_14July19_init_heavy_phra_init_balbara_4 |   |  
0000 | sl_rowIdx_102 | Hilda_14July19_init_heavy_phra_init_balbara_5 |   |  
0000 | sl_rowIdx_103 | Hilda_14July19_init_heavy_phra_init_balbara_6 |   |  
0000 | sl_rowIdx_104 | Hilda_14July19_init_heavy_phra_init_balbara_7 |   |  
0000 | sl_rowIdx_105 | Hilda_14July19_init_heavy_phra_init_balbara_8 |   |  
0000 | sl_rowIdx_106 | Hilda_14July19_init_heavy_phra_init_balbara_9 |   |  
0000 | sl_rowIdx_107 | Hilda_14July19_init_heavy_phra_init_balbara_10

When I try to use this as value of the bundles argument in rename_bundles(), 

`rename_bundles(emuDBhandle = dbHandle,
               bundles = bundles)`

I get an error::

`Error: Evaluation error: could not find function "endsWith".`

**Comment by raphywink** [comment]
endsWith is part of the base package which should be installed by default. Maybe try reinstalling it and see if the error still persists.

**Comment by trblslp** [comment]
Bingo!
