### ISSUE TITLE
rename_bundles() applies different name to folders and their contents

### ISSUE THREAD

**Issue by trblslp** [IPS-LMU/emuR#220]
If I export a seglist to text collection, it generates text and wav files with 'sl_rowIdx_1', 'sl_rowIdx_2' etc. 
<img width="195" alt="Screen Shot 2019-08-14 at 10 28 20 am" src="https://user-images.githubusercontent.com/36254208/63137257-d235cc80-c018-11e9-855f-867dc61c3d8c.png">

I then import these files as text collection, and want to rename the bundles in order to keep the metadata about each recording. Let's say I have 10 tokens of 2 words. I create a dataframe with the old and new names, like so ('session' column omitted):

name<chr> | name_new<chr>
-- | -- 
sl_rowIdx_1 | Hilda_14July19_init_heavy_phra_init_balbara_1
sl_rowIdx_2 | Hilda_14July19_init_heavy_phra_init_balbara_2
sl_rowIdx_3 | Hilda_14July19_init_heavy_phra_init_balbara_3
sl_rowIdx_4 | Hilda_14July19_init_heavy_phra_init_balbara_4
sl_rowIdx_5 | Hilda_14July19_init_heavy_phra_init_balbara_5
sl_rowIdx_6 | Hilda_14July19_init_heavy_phra_init_balbara_6
sl_rowIdx_7 | Hilda_14July19_init_heavy_phra_init_balbara_7
sl_rowIdx_8 | Hilda_14July19_init_heavy_phra_init_balbara_8
sl_rowIdx_9 | Hilda_14July19_init_heavy_phra_init_balbara_9
sl_rowIdx_10 | Hilda_14July19_init_heavy_phra_init_balbara_10
sl_rowIdx_11 | Hilda_14July19_init_heavy_phra_init_Dalgarra_1 
sl_rowIdx_12 | Hilda_14July19_init_heavy_phra_init_Dalgarra_2
sl_rowIdx_13 | Hilda_14July19_init_heavy_phra_init_Dalgarra_3
sl_rowIdx_14 | Hilda_14July19_init_heavy_phra_init_Dalgarra_4
sl_rowIdx_15 | Hilda_14July19_init_heavy_phra_init_Dalgarra_5
sl_rowIdx_16 | Hilda_14July19_init_heavy_phra_init_Dalgarra_6
sl_rowIdx_17 | Hilda_14July19_init_heavy_phra_init_Dalgarra_7
sl_rowIdx_18 | Hilda_14July19_init_heavy_phra_init_Dalgarra_8 
sl_rowIdx_19 | Hilda_14July19_init_heavy_phra_init_Dalgarra_9 
sl_rowIdx_20 | Hilda_14July19_init_heavy_phra_init_Dalgarra_10

When I run `rename_bundles()`, it names the bundle folders exactly as hoped:

<img width="393" alt="Screen Shot 2019-08-16 at 11 09 36 am" src="https://user-images.githubusercontent.com/36254208/63137276-e8438d00-c018-11e9-8450-b0ca2e8edae1.png">

The contents are fine for the first 10 items:

<img width="786" alt="Screen Shot 2019-08-16 at 11 09 50 am" src="https://user-images.githubusercontent.com/36254208/63137303-0d380000-c019-11e9-8701-928acc1668c4.png">

But then after that it gets messy:

<img width="794" alt="Screen Shot 2019-08-16 at 11 09 59 am" src="https://user-images.githubusercontent.com/36254208/63137320-1aed8580-c019-11e9-9f44-f0afe988d7f3.png">

Notice the .wav has been renamed as if it were an 11th token of the first word(?) and there is an `_annot.json` file named this way, as well as one named properly – i.e. the same as the bundle folder. Also, the .wav file has not been copied, just wrongly renamed. In the example above, it is still the recording of the first token of 'Dalgarra' as it says in the folder name, not a token of 'balbara' as its filename suggests.

**Comment by raphywink** [comment]
That def. shouldn't happen. I just looked at the `rename_bundles()` code and I can't see anything that looks wrong there (might be missing something though). Could you maybe create a reproducible example emuDB + code so I can test it on my machine to see what is going on here?

**Comment by trblslp** [comment]
Will this do?
https://gitlab.unimelb.edu.au/pnyhuis/rename_bundles_example 
The repo contains an Rmd file and a folder with the exported text collection. The code in the Rmd will generate an emuDB from the txt collection.

**Comment by trblslp** [comment]
@raphywink any progress on this?

**Comment by raphywink** [comment]
Was just able to reproduce the issue. Will try to fix the issue ASAP (hopefully today).

**Comment by raphywink** [comment]
So the issue was sub-string regex matching and replacing those matches in the new names: sl_rowIdx_1 vs sl_rowIdx_10 (sl_rowIdx_1 also matches sl_rowIdx_10).

**Comment by trblslp** [comment]
you're a living legend, raphael

**Comment by raphywink** [comment]
shucks *blush*
