### ISSUE TITLE
dur gives error

### ISSUE THREAD

**Issue by catalinat** [IPS-LMU/emuR#221]
I just did a simple query and wanted to get some duration values 

> FWsyl <- emuR::query(FrenchWords, "[#SYL =~.* ^ TOK == X]")

> FWsyl$syl_dur <- dur(FWsyl)

But instead I got: 

> Error in UseMethod("dur") : 

  no applicable method for 'dur' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

From https://cran.r-project.org/web/packages/emuR/emuR.pdf I had assumed that the use of dur() wouldn't change. What went wrong? Thanks

**Comment by raphywink** [comment]
`dur()` is a class method of the legacy emuRsegs & emusegs S3 classes. As of version 2.0.0 of emuR we have abandoned these custom classes and instead return an object of the widely used tibble class (which is basically a data frame). This means the `dur()` function isn't available any more (unless you specify the resultType to be either emuRsegs or emusegs). That being said, it is super super simple to calculate the duration:

```{r}
FWsyl <- emuR::query(FrenchWords, "[#SYL =~.* ^ TOK == X]")
FWsyl$syl_dur <- FWsyl$end - FWsyl$start
```

**Comment by catalinat** [comment]
Thanks for the reply! It's a shame that function doesn't exist anymore it just made things go smoother but the other way is just fine. Perhaps it shouldn't be in the manual since it is somehow misleading.
