### ISSUE TITLE
get_trackdata() will not accept tibbles/dfs with non-<chr> columns

### ISSUE THREAD

**Issue by kirbyj** [IPS-LMU/emuR#223]
```create_emuRdemoData(dir = tempdir())
path2ae = file.path(tempdir(), "emuR_demoData", "ae_emuDB")
ae = load_emuDB(path2ae, verbose = F)
sl = query(ae, "[Syllable == S ^ Text == amongst]”)
td = get_trackdata(ae, sl, ssffTrackName = "fm")
```

`INFO: parsing 1 fms segments/events
  |================================================================| 100%
`

However, if the columns are transformed to factors:

```
sl_fct <- sl %>% mutate_if(is.character, as.factor)
td = get_trackdata(ae, sl_fct, ssffTrackName = "fm")
```
```
INFO: parsing 1 fms segments/events
  |                                                                |   0%Error in get_trackdata(ae, sl, ssffTrackName = "fm") : 
  Following utts entry not found: 
In addition: Warning message:
Unknown or uninitialised column: 'utts’.
```

**Comment by raphywink** [comment]
So I just remembered why I don't like factors :-):
```r
splUtt = c(seglist$session[1], seglist$bundle[1])
```
gives you?
```r
c(1,1)
```
That is pretty yucky in my opinion. I could however do the reverse of your `mutate_if` at the start of the functions though.

**Comment by kirbyj** [comment]
I don't think I understand what your example is meant to return... but there do seem to be cogent reasons for avoiding factors.

However, for plotting and modeling, it often seems like factors are exactly what you want. Do you just do the transforms dynamically at the relevant stage?

**Comment by raphywink** [comment]
Sorry should have made the code example clearer: 

```r
path2ae = file.path(tempdir(), "emuR_demoData", "ae_emuDB")
ae = load_emuDB(path2ae, verbose = F)
sl = query(ae, "[Syllable == S ^ Text == amongst]")
sl_fct <- sl %>% mutate_if(is.character, as.factor)
c(sl_fct$session[1], sl_fct$bundle[1])
```
It just has to do with the conversion of characters to integers and associating them with level names instead. That is just how factors work, it can just be confusing AF (maybe just 4 me?) if you then index a vector and get an int where you would expect something else.

> Do you just do the transforms dynamically at the relevant stage?

yes that is basically what I tend to do (e.g. just add the factors right be4 plotting if the function needs it)
