### ISSUE TITLE
Error using write_bundleList() with emuR versions 2.0.4 and 2.0.4.9003

### ISSUE THREAD

**Issue by brisaann** [IPS-LMU/emuR#228]
1. Install emuR (version 2.0.4)
`install.packages("emuR")`
`library(emuR, warn.conflicts = F)`

2. Assuming the db is already created.. Create bundle list to store comments
`bndl = list_bundles(db)`
`write_bundleList(db, name = "french_data", bndl)`

`Error in write_bundleList(db, name = "french_data", bndl) : 
  could not find function "write_bundleList"`

AND
1.  Install newest emuR (version 2.0.4.9003) and update All relevant packages
`devtools::install_github("IPS-LMU/emuR")`
`library(emuR, warn.conflicts = F)`

2. Assuming the db is already created.. Create bundle list to store comments
`bndl = list_bundles(db)`
`write_bundleList(db, name = "french_data", bndl)`

`Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs'`

**Comment by raphywink** [comment]
So the first 2 points make sense as it isn't in the version released on CRAN. I just tried:
```r
devtools::install_github("IPS-LMU/emuR")
library(emuR, warn.conflicts = F)
db = load_emuDB("~/Desktop/emuR_demoData/ae_emuDB/")
bndls = list_bundles(db)
write_bundleList(db, "test", bndls)
```
and that worked without any issues. I also am on the latest R release and all my packages are up to date. Could you maybe retry it? Maybe updating ur other packages (error is from outside of emuR anyway)

**Comment by brisaann** [comment]
Yes, I got it to work now-- had to reinstall R.  It's unfortunate that this is usually the fix.  Thank you!
