### ISSUE TITLE
Why does my serve() command give me the error message: Error parsing wav file: Wav read error: AudioFormat not 0 or 1 but 65534?

### ISSUE THREAD

**Issue by BlockThatCue** [IPS-LMU/emuR#229]
I tried to use emuR and webEmu (in Studio and my default browser is Safari) by creating a db from corpus data that I have on my computer. My small test corpus consists of three wav files and three TextGrids. The wav files have a sample rate of 44,1 kHz, with 16 bits per sample, and one channel (mono). The wav files are 10 minutes each.  

I can create a db, and the `summary(db_handle)` indicates that it has content:

> Name:	 kec-probeer 
UUID:	 ee8073d3-b594-4b3e-b773-1a429f8ccf98 
Directory:	 []/kec-probeer_emuDB 
Session count: 1 
Bundle count: 3 
Annotation item count:  14276 
Label count:  14276 
Link count:  0 
Database configuration:
SSFF track definitions:
NULL
Level definitions:
      name    type nrOfAttrDefs attrDefNames
1    words SEGMENT            1       words;
2 segments SEGMENT            1    segments;
3 canonIPA SEGMENT            1    canonIPA;
4 morphTag SEGMENT            1    morphTag;
Link definitions:
NULL

However, the `serve(db_handle)` results in this error message:

> Error parsing wav file: Wav read error: AudioFormat not 0 or 1 but 65534

Why do I get this error message, what does the error message mean, and what do I need to do to solve it?
Best

Ruben

**Comment by raphywink** [comment]
From here: http://soundfile.sapp.org/doc/WaveFormat/:
AudioFormat: "PCM = 1 (i.e. Linear quantization); Values other than 1 indicate some form of compression."

**Comment by BlockThatCue** [comment]
As far as I know these files were created with praat and saved with the normal save as WAV file.. method... I'll try and

**Comment by raphywink** [comment]
Ok perfect! Glad it worked itself out...
