### ISSUE TITLE
PDF of EMU-SDMS manual?

### ISSUE THREAD

**Issue by monicawagner** [IPS-LMU/emuR#238]
Hello,

This is probably just me being silly, but I get an "404: File not found" error when I try to access "https://ips-lmu.github.io/The-EMU-SDMS-Manual/_main.pdf" or ".epub". Is there somewhere else/another way I can access an easily printable version?

Thanks,
Monica

**Comment by raphywink** [comment]
Hey,

strange that the link is wrong in the bookdown output. Here is the correct link: https://github.com/IPS-LMU/The-EMU-SDMS-Manual/raw/master/_book/_main.pdf
Will have a look at this in a bit and will keep the issue open until then.

Best

**Comment by monicawagner** [comment]
Thank you!

**Comment by raphywink** [comment]
Download is now working
