### ISSUE TITLE
Add optional selection of levels in convert.TextGridCollection.to.emuDB

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#24]
Sometimes it would be useful to just load selected levels from a TextGrid collection.
E.g. all TextGrids of a collection contain a level word and phonetic but SOME of them also contain a level syllable. Such a collection would not load, because inconsistent. If you speciffy that only levels word and phonetic are to be loaded, it would work.

**Comment by raphywink** [comment]
6d86dfff065768d8b4df0da466c20ee32d3fae84 implements this. The convert.TextGridCollection.to.emuDB now has the additional parameter: `tierNames` which is a character vector specifying the names of the tiers you wish to convert.
