### ISSUE TITLE
importing a collection of json annotation files generated by BAS web services

### ISSUE THREAD

**Issue by vdca** [IPS-LMU/emuR#246]
I have run a BAS pipeline on a bunch of files. As a result, I have a directory with many `*_annot.json` files. I wish to populate an EMU DB with these annotation files. I have used the `import_mediaFiles()` function to import the wav files. I understand there's also the function `add_files()`, but it doesn't seem appropriate here, since the annotation files I want to import do not follow the standard basename+extension format.

I'm probably missing something here, since the output annotation of the BAS web service should be easy to import into an existing EMU DB structure. There's also the possibility of running a function like `runBASwebservice_*()`, but these seem to be less flexible than using custom API calls.

**Comment by raphywink** [comment]
So just to clarify: 

- u have a bunch of audio files
- u send those to the BAS pipeline REST endpoint using CURL (or equivalent) with output format `annot.json`
- u then receive an `annot.json`file that doesn't have the base name of the audio file

If so could you send me an example of how u are calling the web service?

**Comment by vdca** [comment]
Sorry, I was not clear enough. The first two points you mention are correct, but the third one is not:

- the `annot.json` file I get from the CURL call _does_ have the base name of the audio file.

The issue is that the function `add_files()` expects files with the format `basename.extension`, and the annotation files I get from the BAS pipeline follow the format `basename_annot.json`. The additional `_annot` in the filename prevents the `add_files()` function from working as expected with this kind of files.

`Error in add_files(...) : more or less than one bundle found that matches the base name of the file.`
