### ISSUE TITLE
Problem with convert_TextGridCollection(): Couldn't find a match for [intervals|points] 

### ISSUE THREAD

**Issue by qiangxiajinjin** [IPS-LMU/emuR#258]
I have a problem with converting TextGrids into the emuDB format. When I try the following code `

```
library(emuR)
pathCol = "~/MA-data/analyse/collection"
convert_TextGridCollection(pathCol,
                           dbName = "v2",
                           targetDir = "~/MA-data/analyse/collection")
```

for my data collection, I get the following error message:

> in TextGridToBundleAnnotDFs(tgPath, sampleRate = 2000, name = "tmpBundleName",  : 
>   Couldn't find a match for [intervals|points]:\s*size in ~/MAdata/analyse/collection/bg/bg_f_diapix1_m14m13_ch1.TextGrid!!! The first few lines of the current tier are (might help spot the error...): NA"

I don't understand why there is no match for the .TextGrid file, because I do have a .wav file sharing the same basename. Or does it mean something else rather than a wav counterpart? 

> list.files("~/MAdata/analyse/collection/bg")
[1] "bg_f_diapix1_m14m13_ch1.TextGrid" "bg_f_diapix1_m14m13_ch1.wav"      "bg_f_diapix1_m14m13_ch2.TextGrid"
[4] "bg_f_diapix1_m14m13_ch2.wav"     

I don't understand the error `The first few lines of the current tier are (might help spot the error...): NA` either. As far as I see in the mentioned TextGrid, the "lines" are not empty. Do I take the message wrong again? 

<img width="417" alt="Screenshot 2022-04-06 at 10 24 26" src="https://user-images.githubusercontent.com/97401975/161930249-10450645-8245-4f5a-8777-dc51a8c1d83d.png">

**Comment by qiangxiajinjin** [comment]
The reason why it does not work is probably that two tiernames in the TexgGrid are (almost) identical (one is uppercase and the other is lowercase). After I rename them, it works well 🥲

**Comment by qiangxiajinjin** [comment]
> 

No, renaming tiers does not solve the problem. I got the same error message again... 😞 
`in TextGridToBundleAnnotDFs(tgPath, sampleRate = 2000, name = "tmpBundleName",  : 
  Couldn't find a match for [intervals|points]:\s*size in ~/MA-data/analyse/collection/bg/bg_f_diapix1_m14m13_ch1.TextGrid!!! The first few lines of the current tier are (might help spot the error...): 
NA`

**Comment by rpuggaardrode** [comment]
This seems to be a problem with the 'short' TextGrid format. When you save a TextGrid from Praat, you'll get the option to "Save as text file..." or "Save as short text file...". I had the same issue and when I 'saved as text file' instead of 'as short text file', the problem was solved.

**Comment by qiangxiajinjin** [comment]
> This seems to be a problem with the 'short' TextGrid format. When you save a TextGrid from Praat, you'll get the option to "Save as text file..." or "Save as short text file...". I had the same issue and when I 'saved as text file' instead of 'as short text file', the problem was solved.

**Comment by qiangxiajinjin** [comment]
> This seems to be a problem with the 'short' TextGrid format. When you save a TextGrid from Praat, you'll get the option to "Save as text file..." or "Save as short text file...". I had the same issue and when I 'saved as text file' instead of 'as short text file', the problem was solved.

Thanks a lot! It really solved my problem! Exactly the "short text file" caused the error.
