### ISSUE TITLE
Display number of items found after query

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/emuR#34]
The legacy emu package displayed how many records it read after query completion
```R
> res = emu.query('ae', '*', 'Phonetic=n')
moving data from Tcl to R
Read 12 records # this is how many it found
``` 
As a user pointed out it would be handy to see the number of items found directly after a query (without having to call a function like `dim` or `length`). I think it would be handy to have some form of output along the lines of

```R
> res = query('ae', 'Phonetic=n')
Found 12 items
```
What do you think?

**Comment by klausj** [comment]
In general I prefer the good old UNIX philosophy rule of silence. If the function is used in a script, I think it's better if it does not print unnecessary output. But we could add an verbose option parameter for this.

**Comment by raphywink** [comment]
I agree... closing issue! Lets just see if anyone else complains and then we can think about it some more...
