### ISSUE TITLE
emuR::load_emuDB : does not respect umask settings

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#47]
When loading an emu DB the first time, the file cache is created in the root dir of the emu DB.
For some reason R does not respect the umask settings (here: 0002) of the user when creating the cache file. Instead the umask 0022 (in UNIX rights rw-r--r--) is used. Hence the group has no right to write. This can be cumbersome when a group of users is working on the DB, because then the load reports an error when trying to load the next time by a different user of the group, since the cache file must be opened writeable.

**Comment by klausj** [comment]
It seems that RSqlite or sqlite sets the permissions on its own. To set the right permissions we would have to call Sys.chmod() after creation of the cache, which would be quirky and may have side effects.
So we decided **not** to set the permissions programatically from the emuR package.
