### ISSUE TITLE
Communication Error with EmuLabeller

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#50]
In EmuLabeller:
Communication error with server! Error message is: kann Verbindung nicht öffnen

Tested with local IPS emuR DB that was build a while ago:

--------------------
library(devtools)
install_github("IPS-LMU/emuR")
library(emuR)
ci = load_emuDB("/vdata/BAS/IPS-PROJECTS/VeronikaNeumeyerPhD/Cluster_CIvsKG")
summary_emuDB(ci)
Name:    Cluster_CIvsKG 
UUID:    18bca4c7-2d9c-45ef-9a38-b565f3870f20 
Directory:       /vdata/BAS/IPS-PROJECTS/VeronikaNeumeyerPhD/Cluster_CIvsKG 
Session count: 1 
Bundle count: 3467 
Annotation item count:  133242 , links count:  87201 

Database configuration:

Level definitions:
ORT     type:    SEGMENT 
        Attribute definitions:
        ORT     type:    STRING 

KAN     type:    SEGMENT 
        Attribute definitions:
        KAN     type:    STRING 

MAU     type:    SEGMENT 
        Attribute definitions:
        MAU     type:    STRING 

SEG     type:    SEGMENT 
        Attribute definitions:
        SEG     type:    STRING 

POT     type:    EVENT 
        Attribute definitions:
        POT     type:    STRING 

Link definitions:
ORT     ->      KAN     ONE_TO_MANY 
KAN     ->      MAU     ONE_TO_MANY 
ORT     ->      SEG     ONE_TO_MANY 
SEG     ->      POT     ONE_TO_MANY 
serve(ci)
Navigate your browser to the EMU-Webapp URL: http://ips-lmu.github.io/EMU-webApp/
Server connection URL: ws://localhost:17890
To stop the server press EMU-Webapp 'clear' button or reload the page in your browser.
emuR websocket service established
Error:  kann Verbindung nicht öffnen
-----------------------------

Then I tried to load again using the file cache (much faster), but the effect is the same.
Then loaded another emuR DB that was build more recently (Braidwood)

----------------------------------
purge_all_emuDBs()
brwd = load_emuDB("/vnbdata/emuDBs2/Braidwood/Braidwood")
serve(brwd)

-> no error!

**Comment by raphywink** [comment]
The `annotJSON` file in `Cluster_CIvsKG/0000_ses/C1E1JUWE1039Cr_01_h2_bndl` contains following entry:

```json
"annotates": "0000_ses/C1E1JUWE1039Cr_01_h2_bndl/C1E1JUWE1039Cr_01_h2.wav"
```

This should not contain the session and bundle paths but should be a relative path directly to the wav file (by that I mean `"annotates": "C1E1JUWE1039Cr_01_h2.wav"`)

could it be that this emuDB was converted a while back? The convert_legacyEmuDB_by_name_to_emuDB() used to produce it that way but we changed that behavior a fair while ago... 

The easiest fix would be to just reconvert the database. If that is not possible I could write you a small script that fixed those entries.
