### ISSUE TITLE
empty query() result behaves strange 

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#51]
When a emuR query() results in an empty list, such as:

timit = load_emuDB("/vdata/BAS/TIMIT/EMU/TIMIT")
word.sl = query(timit,"word=~'sh'")

then the list is properly printed as

word.sl
segment  list from database:  TIMIT 
query was:  word=~'sh' 
[1] labels  start   end     session bundle  level   type   
<0 Zeilen> (oder row.names mit Länge 0)

and:

dim(word.sl)
[1]  0 14

*but* not, if a line index is used, such as:

word.sl[20,]
segment  list from database:  TIMIT 
query was:  word=~'sh' 
   labels start  end session bundle level type
NA   <NA>  <NA> <NA>    <NA>   <NA>  <NA> <NA>

This might be problematic when further processing query() results without checking for dim().

**Comment by raphywink** [comment]
This is the same behavior as a normal `data.frame`:

```r
> df = data.frame(a = character(), b = numeric(), stringsAsFactors = F)
> dim(df)
[1] 0 2
> df[20,]
      a  b
NA <NA> NA
```

I don't think that it would be a good idea to differ in behavior from the `data.frame` function as a `emuRsegs` object is a superclass of `data.frame`.
