### ISSUE TITLE
emuR::convert_legacyEmuDB_to_emuDB() does not convert labelGroups

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#54]
For example the Emu legacy /vdata/corpora/emu_templates/KielCorpusRead.tpl contains 
label group definitions such as:

legal Phonetic stop p t k b d g

After running the convert...() the level Definition looks like

            "name": "Phonetic",
            "type": "SEGMENT",
            "attributeDefinitions": [
                {
                    "name": "Phonetic",
                    "type": "STRING"
                },
                {
                    "name": "Autoseg",
                    "type": "STRING"
                },
                {
                    "name": "SinfoPhon",
                    "type": "STRING"
                },
                {
                    "name": "LexAccent",
                    "type": "STRING"
                }
            ]
        }

(See /vdata/BAS/KielCorpusRead/KielCorpusRead/KielCorpusRead_DBconfig.json)
So, no labelGroup 'stop' here.

**Comment by klausj** [comment]
It does not convert if the label group is assigned to a level with more than one attributes.
