### ISSUE TITLE
emuR::convert_legacyEmuDB_to_emuDB() : default entry in DBconfig

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#55]
Feature request:
emuR::convert_legacyEmuDB_to_emuDB() should activate the 'Show hierarchy' button in the DBconfig file by default, please.

(I can't mark this issue as a feature request; so could please somebody with more github power do that for me? Thank you.)

**Comment by florianschiel** [comment]
In same direction:
emuR::convert_legacyEmuDB_to_emuDB() should make entries in the 'default' perspective under signalCanvases for the first 10 track definitions found in the legacy template file. The reason I'd rather constrain that to max 10 tracks is: some EMA DBs have hundreds of track definitions, and I guess the webapp would not be happy to display all those by default...

**Comment by raphywink** [comment]
New issue opened for max 10 tracks for default perspective. See here #58
