### ISSUE TITLE
Error handling when user has no write permissions to SQLite cache

### ISSUE THREAD

**Issue by klausj** [IPS-LMU/emuR#63]
I the user has no write permissions to SQLite cache DB and the cache needs to be updated the load_emuDB function throws an error, but does not cleanup (purge) the database.
(To update the cache the user needs write permissions to the emuDB base directory too;
SQLite needs to write temporary files to the directory, where the .sqlite databse file lies.) 

```
> dbNm=load_emuDB("pathToDb")
[1] "Reloading _DBconfig.json ..."
 Hide Traceback

 Rerun with Debug
 Fehler in sqliteSendQuery(con, statement, bind.data) : 
  rsqlite_query_send: could not execute1: attempt to write a readonly database 
```

Loading failed, but list_emuDBs() lists the database.

**Comment by raphywink** [comment]
the load_emuDB function should "just" crash now (probably not very gracefully...) but a purge isn't necessary anymore as nothing is returned on failure. Can we close this issue? Or should we check for read/write permission at the beginning of the load_emuDB function and throw a "decent" error?

**Comment by raphywink** [comment]
`load_emuDB()` now checks for read only emuDB -> if so copy caches to `tempdir()` and opens the connection
