### ISSUE TITLE
handle hangs around after convert_TextGridCollection_to_emuDB

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/emuR#75]
After a call to  `convert_TextGridCollection_to_emuDB()` the handle does not get deleted. This causes a load after the conversion to fail.

@klausj obviously the call to `.purge.emuDB(dbUUID)` at the end of the function (https://github.com/IPS-LMU/emuR/blob/master/R/convert.TextGridCollection.R#L200) isn't the right thing to do any more. What do I have to call? `purge_emuDB()`?

**Comment by klausj** [comment]
Yes, purge_emuDB(dbUUID=uuid,interactive=F).
