### ISSUE TITLE
get_trackdata : works only for emuR DB with homogenous sampling rates

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#97]
emuR DB allows in-homogeneous sampling rates in the WAV files.
However, get_trackdata does not: if applied to such a loaded emuR DB the user gets a generic error message that is not helpful. (test emuR DB in /vdata/BAS/Rhapsodie/)
There is no hint in the help page about that either.

Since the outcome of most wrassp functions are dependent on the sampling rate, the application of get_trackdata in many cases does not make sense (e.g. you cannot calculate the same-sized  DFT spectrum across different sampling rates). Insofar it would be nice, if get_trackdata would check the emuR DB first for homogeneity and terminate with a proper error message if sampling rates are not homogeneous (and has some remark about that in the help section).

**Comment by raphywink** [comment]
Should this really be dealt with with a error or is a warning sufficient?
