### ISSUE TITLE
write.emusegs / read.emusegs : class emuRsegs is stripped

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#98]
When a user saves a emuRsegs object using the legacy Emu function write.emusegs, and later restore the object with read.emusegs, the resulting object is of class emusegs, thus stripped of some columns, and not to be used in emuR functions such as requery_... or get_trackdata.

The proper solution would be to have generic S3 write / read function for these classes.
A work-around would be at least a warning of write.emusegs when called with a emuRsegs object that data are lost in the stored object (and maybe a hint to use save / load instead).

**Comment by raphywink** [comment]
We originally said that we would not support any read/write functionality for the new `emuRsegs` object. If people wish to save the objects to disc they should simply use R's `save` function if they wish to preserve all the information of that object (why reinvent the wheel with another text format (like the old emusegs file format)). As the `emuRsegs` class doesn't implement any read/write function but superclasses the `emusegs` class, the `emusegs` class methods are applied -> loss of information.
 
Maybe we should implement the S3 methods for the "emuRsegs" object after all but simply say "stop('please use the save() function instead')". What do you think?

**Comment by florianschiel** [comment]
Yes, I agree. (To my opinion the old function should be removed, but due to backward compatibility we better not do that.)

**Comment by florianschiel** [comment]
Sorry, did close the issue by accident.

**Comment by klausj** [comment]
I agree, too.

**Comment by klausj** [comment]
The reason why we did not implement the method is that write() is not a generic method. Though write.emusegs uses the S3 naming scheme it is not an S3 method.
I implemented the workaround now which generates a warning if write.emusegs is used with an emuRsegs object. OK?
